# 头部菜单，title: link
menu:
  QQ: http://wpa.qq.com/msgrd?v=3&uin=794763733&site=qq&menu=yes
  Github: https://github.com/QQ794763733
  Email: http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=794763733@qq.com

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
    #需要人陪
  - http://www.ytmp3.cn/down/50235.mp3
    #See you again
  - http://www.ytmp3.cn/down/51245.mp3
    #一万次悲伤
  - http://www.ytmp3.cn/down/49141.mp3
    #海阔天空
  - http://www.ytmp3.cn/down/49625.mp3
    #傲寒
  - http://www.ytmp3.cn/down/38749.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: ''
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: QQ794763733

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
